// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimeiraApiWorkshop.DataBase;

namespace PrimeiraApiWorkshop.DataBase
{
    [DbContext(typeof(NpgContext))]
    [Migration("20211210190441_Brasil")]
    partial class Brasil
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PrimeiraApiWorkshop.Models.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Ano")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ano");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.HasKey("Id");

                    b.ToTable("tb_vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
